"""
Generation data models for TestPilot AI.

These Pydantic models represent the structured output produced by the
TestGenerationAgent and test generation pipeline.

Design rules:
  - Every field has a sensible default so partial construction is always safe.
  - All Path fields are stored as strings for JSON serialisation compatibility.
  - No secrets, credentials, or API keys are stored.
  - Distinguishes generated test code from explanatory text.
  - Captures syntax and AST validation outcomes explicitly.
"""

from __future__ import annotations

from datetime import UTC, datetime
from enum import StrEnum

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class GenerationStatus(StrEnum):
    """Overall outcome of a test generation run."""

    SUCCESS = "success"
    """Valid pytest tests were generated and passed AST validation."""

    PARTIAL = "partial"
    """Some tests were generated but one or more targets encountered issues."""

    SYNTAX_ERROR = "syntax_error"
    """The generated code could not be parsed by Python's AST parser."""

    NO_TESTS_FOUND = "no_tests_found"
    """Code was syntactically valid Python, but contained no test functions/classes."""

    EMPTY_RESPONSE = "empty_response"
    """The LLM returned an empty or whitespace-only response."""

    LLM_ERROR = "llm_error"
    """An error occurred while communicating with the LLM provider."""

    VALIDATION_ERROR = "validation_error"
    """Input parameters or repository path were invalid."""

    ERROR = "error"
    """An unexpected fatal generation error occurred."""


# ---------------------------------------------------------------------------
# Sub-models
# ---------------------------------------------------------------------------

class GeneratedTestCase(BaseModel):
    """Metadata for an individual test function or method found in generated code."""

    name: str
    """Test function or method name (e.g. 'test_celsius_to_fahrenheit')."""

    target_function: str = ""
    """Name of the module function or class being tested, if inferred."""

    line: int | None = None
    """Line number where the test function is defined in the generated code."""

    is_async: bool = False
    """True if defined with async def."""

    has_docstring: bool = False
    """True if the test function includes a docstring."""


class GeneratedTestFile(BaseModel):
    """Structured record for a single generated test file."""

    file_path: str
    """Repository-relative destination path for the test file."""

    target_source_file: str
    """Repository-relative path of the source file being tested."""

    code: str = ""
    """The cleaned, runnable Python test code extracted from model output."""

    test_cases: list[GeneratedTestCase] = Field(default_factory=list)
    """Individual test cases discovered in the validated code."""

    is_valid: bool = False
    """True if the code parsed without syntax errors and contains test functions."""

    validation_error: str | None = None
    """Error message if AST parsing or validation failed."""

    written_to_disk: bool = False
    """True if the file was actually written to the filesystem."""

    @property
    def test_count(self) -> int:
        """Number of test cases in this file."""
        return len(self.test_cases)

    @property
    def test_names(self) -> list[str]:
        """Names of all test cases in this file."""
        return [t.name for t in self.test_cases]


# ---------------------------------------------------------------------------
# Top-level Generation Report
# ---------------------------------------------------------------------------

class GenerationReport(BaseModel):
    """
    Complete structured report of a test generation run.

    Created by TestGenerationAgent / generate_tests().
    Stored in SessionContext.generation_report and persisted as JSON.
    """

    repository_path: str
    target_files: list[str] = Field(default_factory=list)
    status: GenerationStatus = GenerationStatus.ERROR

    started_at: datetime = Field(
        default_factory=lambda: datetime.now(tz=UTC)
    )
    completed_at: datetime | None = None
    duration_seconds: float = 0.0

    generated_files: list[GeneratedTestFile] = Field(default_factory=list)

    explanation: str = ""
    """Explanatory or contextual text generated by the model outside code blocks."""

    raw_response: str = ""
    """Raw unmodified LLM completion text."""

    model: str = ""
    """Model identifier used for generation."""

    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0

    errors: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)

    # ------------------------------------------------------------------
    # Convenience properties
    # ------------------------------------------------------------------

    @property
    def total_tests_generated(self) -> int:
        """Total count of valid test cases across all generated files."""
        return sum(f.test_count for f in self.generated_files if f.is_valid)

    @property
    def has_valid_tests(self) -> bool:
        """True if at least one valid test case was generated."""
        return self.total_tests_generated > 0

    @property
    def valid_files(self) -> list[GeneratedTestFile]:
        """List of successfully validated generated files."""
        return [f for f in self.generated_files if f.is_valid]

    @property
    def all_test_names(self) -> list[str]:
        """Flat list of all generated test function names."""
        names: list[str] = []
        for f in self.generated_files:
            if f.is_valid:
                names.extend(f.test_names)
        return names
